### ISSUE TITLE
Path existance check assumes "definisions" in schema

### ISSUE THREAD

**Issue by mateuszpawlik** [nextflow-io/nf-schema#13]
I have a simple schema with three parameters. One of them is a required path. I used the nf-core schema build which generated that schema. Since I have only three parameters, I didn't think about grouping them. The "exists" key wouldn't work. It took me some time to figure out that [collecting parameters with "exists" key set](https://github.com/nextflow-io/nf-validation/blob/26f56310c397ca987ba9510abbddcc3d77abf0c6/plugins/nf-validation/src/main/nextflow/validation/SchemaValidator.groovy#L322) assumes "definitions" key in the schema:

https://github.com/nextflow-io/nf-validation/blob/26f56310c397ca987ba9510abbddcc3d77abf0c6/plugins/nf-validation/src/main/nextflow/validation/SchemaValidator.groovy#L306

Once I grouped my parameters in "definitions" the existence check was triggered.

Are group "definitions" mandatory?

**Comment by nvnieuwk** [comment]
`nf-schema` has now been released, this contains all improvements + more from nf-validation v2.0. Can you try again with the new plugin?

**Comment by nvnieuwk** [comment]
This should be fixed now, feel free to reopen if you were to encounter more issues with this
