### ISSUE TITLE
nf-validation fails on validateParameters when schema_input.json is not standard

### ISSUE THREAD

**Issue by maxulysse** [nextflow-io/nf-schema#19]
error:
```
ERROR ~ Unexpected error [NullPointerException]

 -- Check script 'main.nf' at line: 33 or see '.nextflow.log' file for more details
 ```
 
 pointing to:
 
 ```
 // Validate input parameters
if (params.validate_params) {
    validateParameters()
}
```

I got rid of it by removing the input validation in the `nextflow_schema.json`

cf https://nfcore.slack.com/archives/C056RQB10LU/p1695298538145319

**Comment by nvnieuwk** [comment]
Do you still have this error in `nf-schema`? @maxulysse ?

**Comment by nvnieuwk** [comment]
I think this issue has been solved now, feel free to reopen if you were to encounter it again :)
