### ISSUE TITLE
Feature request: Add an ` or ` option for input params

### ISSUE THREAD

**Issue by matthdsm** [nextflow-io/nf-schema#22]
Hi,

I've got a pipeline that takes different input file types, each with different required fields. Is there a way to one `OR` another field mandatory?

For example
```
if flowcell; then samplesheet, sampleinfo are mandatory
else if fastq: then id,samplenamen... are mandatory
```

**Comment by nvnieuwk** [comment]
@matthdsm can you try this with `nf-schema`?
