### ISSUE TITLE
Schema has allOf, but no definitions

### ISSUE THREAD

**Issue by chriswyatt1** [nextflow-io/nf-schema#32]
Hi, 

I am probably doing something really dumb, but I cannot get ` nf-core schema build` to work.

I have an existing repo (https://github.com/Eco-Flow/synteny), that I migrated to the new json style, but it says:

```
ERROR    [✗] Pipeline schema does not follow nf-core specs:                                                                  
          Schema has allOf, but no definitions                                                                               
ERROR    Existing pipeline schema found, but it is invalid: nextflow_schema.json                                             
INFO     Please fix or delete this file, then try again. 
```

I then played around with my json file to make it as minimal as possible, but always get this error. 

I then tried the example json: https://nextflow-io.github.io/nf-schema/latest/nextflow_schema/nextflow_schema_examples/ to see if this makes the same error, and for me it does. 

I use this in my main.nf:
`include { validateParameters; paramsHelp; paramsSummaryLog } from 'plugin/nf-schema'`
Plus:
```
plugins {
  id 'nf-co2footprint@1.0.0-beta'
  id 'nf-schema@2.0.0'
  id 'nf-amazon@2.1.4'
}

```

and I am using `nf-core` tools version 2.13.1. `nextflow` 24.03.0-edge.5908. I have deleted my nf-schema cache

If anyone can see what I am missing, I would be grateful :)

**Comment by chriswyatt1** [comment]
Most likely the version of nextflow. I will retest

**Comment by pcrxn** [comment]
I'm obtaining the same error after migrating an existing workflow to the new style ([nextflow_schema.json](https://github.com/nextflow-io/nf-schema/files/15238795/nextflow_schema.json) attached) with `nf-core=2.13.1`.

**Comment by chriswyatt1** [comment]
From Júlia Mir  : 
nf-core schema build is not yet updated to use the new JSON draft, the one used by nf-schema, so the migration has to be done manually
You can see the docs on how to migrate [here](https://nextflow-io.github.io/nf-schema/latest/migration_guide/)
nextflow-io.github.ionextflow-io.github.io
[Migration guide - nf-schema](https://nextflow-io.github.io/nf-schema/latest/migration_guide/)
